version: '3.1'
services:
 mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - app-network

 redis:
    image: redis:latest
    restart: always
    networks:
      - app-network

 worker:
    build: .
    restart: always
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    volumes:
      - .:/app
    command: python worker.py

volumes:
 mongodb:

networks:
 app-network:
    driver: bridge
