version: '3.1'
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    restart: always
    networks:
      - app-network
    ports:
      - "6379:6379"
  api:
    environment:
      MONGO_URI: "mongodb://mongodb:27017/rmo_database"
      REDIS_URL: "redis://redis:6379"
    build: .
    ports:
      - "800:8080"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    restart: always
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

  worker:
    build: ./app
    command: celery -A tasks.celery_worker worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=mongodb://mongodb:27017/rmo_database
    depends_on:
      - api
      - redis
      - mongodb
    restart: always

volumes:
 mongodb:

networks:
 app-network:
    driver: bridge
